export const COLLECTIONS = [
  // eslint-disable-next-line etc/no-commented-out-code
  // {
  //   id: 1,
  //   image: '/img/drops/1988Dragon_cover-04.png',
  //   title: 'Shared Collection',
  //   price: '3.37',
  //   quantity: 0,
  //   type: 'sand',
  //   special: 'fox-fire',
  //   clothing: 'maroon-yukata',
  //   link: 'marketplace',
  // },
  {
    id: 2,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
  {
    id: 3,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
  {
    id: 4,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
  {
    id: 5,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
  {
    id: 6,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
  {
    id: 7,
    image: '/img/drops/1988dragon.jpg',
    title: '1988 Dragon Collection',
    price: '1',
    quantity: 1,
    type: 'spirit',
    special: 'fox-fire',
    clothing: 'light-kimono',
    link: 'mint',
  },
];
